"""Skill catalog wrapper — mirrors FMelodiaSongSkillRecipe from MelodiaCore C++.

45 skills (Lv1-Lv30) replicated from MelodiaSongSkillLibrary.cpp
and generated by the GMM daemon.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Optional

INSTRUMENTS = ("MusicBox", "Violin", "Drums", "Harp", "Trumpet", "Keyboards")
ELEMENTS = ("Forte", "Tide", "Gale", "Stone", "Radiant", "Umbral", "Arcane")


@dataclass
class MelodiaSongSkillRecipe:
    skill_id: str
    display_name: str
    description: str = ""
    element: str = "Forte"
    instrument: str = "MusicBox"
    mechanic_level: int = 1
    note_pitches: tuple[int, ...] = (60,)
    note_durations: tuple[float, ...] = (0.25,)
    sp_cost: int = 1
    power_scalar: float = 1.0

    def to_dict(self) -> dict:
        d = asdict(self)
        return d


def _build_skill(name: str, pitches: tuple[int, ...], durations: tuple[float, ...],
                 element: str = "Forte", instrument: str = "MusicBox",
                 level: int = 1, sp: int = 1, power: float = 1.0) -> MelodiaSongSkillRecipe:
    return MelodiaSongSkillRecipe(
        skill_id=name.replace(" ", ""),
        display_name=name,
        element=element, instrument=instrument,
        mechanic_level=level, sp_cost=sp, power_scalar=power,
        note_pitches=pitches, note_durations=durations,
    )


DEMO_SKILLS: list[MelodiaSongSkillRecipe] = [
    _build_skill("StarlitPing", (60, 64, 67), (0.25, 0.25, 0.5), "Radiant", "MusicBox", 1, 1, 0.8),
    _build_skill("MoonStep", (62, 66, 69), (0.5, 0.25, 0.5), "Umbral", "MusicBox", 1, 1, 1.0),
    _build_skill("CherryArpeggio", (60, 64, 67, 72), (0.125, 0.125, 0.125, 0.5), "Radiant", "Harp", 2, 1, 0.9),
    _build_skill("TidalChord", (60, 63, 67, 70), (0.5, 0.25, 0.25, 0.5), "Tide", "Harp", 2, 2, 1.1),
    _build_skill("GustStaccato", (64, 67, 71, 64), (0.125, 0.125, 0.125, 0.375), "Gale", "Violin", 3, 1, 0.85),
    _build_skill("StoneOstinato", (60, 60, 62, 64), (0.5, 0.25, 0.25, 0.5), "Stone", "Drums", 3, 2, 1.2),
    _build_skill("ForteFanfare", (60, 67, 72, 76), (0.25, 0.25, 0.5, 0.5), "Forte", "Trumpet", 4, 2, 1.3),
    _build_skill("ArcaneGlissando", (60, 64, 67, 72, 76), (0.125, 0.125, 0.125, 0.25, 0.5), "Arcane", "Harp", 4, 2, 1.15),
    _build_skill("WhisperWind", (64, 62, 60), (0.5, 0.25, 0.75), "Gale", "Violin", 5, 1, 0.75),
    _build_skill("CrystalRain", (72, 76, 79, 84), (0.125, 0.125, 0.25, 0.5), "Radiant", "MusicBox", 5, 2, 1.0),
    _build_skill("EmberStrike", (60, 63, 67, 71), (0.25, 0.125, 0.25, 0.5), "Forte", "Trumpet", 6, 2, 1.25),
    _build_skill("TidalWave", (60, 64, 67, 72, 76), (0.5, 0.125, 0.125, 0.25, 0.5), "Tide", "Harp", 6, 3, 1.35),
    _build_skill("ShadowDance", (62, 66, 70, 73), (0.125, 0.25, 0.125, 0.5), "Umbral", "Violin", 7, 2, 1.1),
    _build_skill("StoneWall", (60, 60, 64, 67), (0.75, 0.25, 0.25, 0.5), "Stone", "Drums", 7, 3, 1.4),
    _build_skill("CelestialChord", (60, 67, 72, 79), (0.5, 0.25, 0.5, 0.75), "Arcane", "Harp", 8, 3, 1.45),
    _build_skill("GaleForce", (67, 71, 76, 72), (0.125, 0.125, 0.375, 0.25), "Gale", "Violin", 8, 2, 1.0),
    _build_skill("LullabyMoon", (62, 66, 69, 73), (0.5, 0.25, 0.5, 0.75), "Umbral", "MusicBox", 9, 2, 0.9),
    _build_skill("PhoenixRise", (60, 64, 67, 72, 76, 84), (0.125, 0.125, 0.125, 0.125, 0.25, 0.75), "Forte", "Trumpet", 9, 4, 1.6),
    _build_skill("TidalResonance", (60, 63, 67, 70, 73, 67), (0.5, 0.125, 0.125, 0.125, 0.25, 0.5), "Tide", "Harp", 10, 3, 1.3),
    _build_skill("CrystalSymphony", (60, 64, 67, 72, 76, 79, 84), (0.125,) * 7, "Radiant", "MusicBox", 15, 4, 1.5),
    _build_skill("ShadowRealm", (62, 66, 70, 73, 78, 82), (0.25,) * 6, "Umbral", "Violin", 15, 4, 1.55),
    _build_skill("StoneCathedral", (60, 64, 67, 72, 76, 60), (0.75, 0.25, 0.5, 0.25, 0.5, 1.0), "Stone", "Drums", 18, 5, 1.7),
    _build_skill("ArcaneStorm", (60, 63, 67, 72, 76, 84, 72), (0.125,) * 7, "Arcane", "Harp", 18, 5, 1.75),
    _build_skill("GaleSymphony", (64, 67, 71, 76, 79, 84), (0.125, 0.25, 0.125, 0.25, 0.5, 0.5), "Gale", "Violin", 20, 4, 1.4),
    _build_skill("ForteCrescendo", (60, 64, 67, 72, 76, 84, 88), (0.25, 0.125, 0.125, 0.25, 0.25, 0.5, 1.0), "Forte", "Trumpet", 20, 5, 1.8),
    _build_skill("TidalEternal", (60, 64, 67, 72, 76, 84, 96), (0.5,) * 7, "Tide", "Harp", 22, 5, 1.85),
    _build_skill("UmbralNocturne", (62, 66, 69, 73, 78, 82, 86), (0.5, 0.25, 0.5, 0.25, 0.5, 0.25, 1.0), "Umbral", "Violin", 24, 5, 1.9),
    _build_skill("RadiantFinale", (60, 64, 67, 72, 76, 84, 88, 96), (0.125,) * 8, "Radiant", "MusicBox", 27, 5, 2.0),
    _build_skill("ElementalFury", (60, 63, 67, 71, 76, 84, 72, 60), (0.25,) * 8, "Arcane", "Harp", 28, 5, 2.1),
    _build_skill("MaestroFinale", (60, 64, 67, 72, 76, 84, 88, 96, 72), (0.125, 0.125, 0.125, 0.25, 0.25, 0.5, 0.25, 0.5, 1.0), "Forte", "Trumpet", 30, 5, 2.5),
]


# Daemon-generated skills (levels 10-19)

DEMO_SKILLS.extend([
    _build_skill("EmberStorm", (72, 76, 79, 84), (0.25, 0.25, 0.25, 0.5),
                 "Forte", "Keyboards", 10, 25, 2.8),
    _build_skill("StoneBarrier", (40, 47, 52), (0.5, 0.5, 0.5),
                 "Stone", "Drums", 11, 18, 1.5),
    _build_skill("VoidLament", (55, 51, 48, 43), (0.5, 0.25, 0.25, 0.5),
                 "Umbral", "Violin", 12, 30, 3.5),
    _build_skill("ArcaneCascade", (60, 64, 67, 72, 76), (0.25, 0.25, 0.25, 0.25, 0.5),
                 "Arcane", "MusicBox", 13, 22, 2.2),
    _build_skill("RadiantBurst", (84, 88, 91, 96), (0.25, 0.25, 0.25, 0.5),
                 "Radiant", "Keyboards", 14, 28, 3.0),
    _build_skill("TempestFury", (76, 79, 84, 88, 91), (0.125,) * 4 + (0.5,),
                 "Gale", "Violin", 15, 35, 4.0),
    _build_skill("TidalCrush", (36, 48, 60, 72), (0.5, 0.25, 0.25, 0.5),
                 "Tide", "Drums", 16, 32, 3.8),
    _build_skill("InfernoWaltz", (72, 76, 72, 79, 72, 84), (0.25,) * 6,
                 "Forte", "Keyboards", 17, 38, 4.2),
    _build_skill("CrystalSanctum", (48, 52, 55, 60), (0.5, 0.5, 0.5, 1.0),
                 "Stone", "MusicBox", 18, 20, 1.0),
    _build_skill("UmbralRequiem", (43, 40, 36, 43, 40, 36, 31), (0.25,) * 7,
                 "Umbral", "Violin", 19, 40, 4.5),
    _build_skill("AstralHarmony", (60, 64, 67, 72, 76, 84), (0.25, 0.25, 0.25, 0.25, 0.25, 0.5),
                 "Arcane", "MusicBox", 20, 35, 3.5),
    _build_skill("SolarRhapsody", (96, 100, 103, 108), (0.25, 0.25, 0.25, 0.75),
                 "Radiant", "Keyboards", 22, 42, 5.0),
    _build_skill("StormChase", (79, 84, 79, 88, 79, 91), (0.125,) * 6,
                 "Gale", "Violin", 24, 30, 2.5),
    _build_skill("AbyssalSong", (36, 48, 60, 48, 36), (0.5, 0.25, 0.5, 0.25, 1.0),
                 "Tide", "Drums", 25, 45, 5.5),
    _build_skill("VoidGate", (36, 31, 43, 31, 36, 31), (0.25,) * 6,
                 "Umbral", "Violin", 29, 55, 7.0),
])

# Healing/buff skills (daemon-generated)
DEMO_SKILLS.extend([
    _build_skill("TidalMend", (60, 64, 67, 72), (0.25, 0.25, 0.25, 0.5),
                 "Tide", "Harp", 10, 15, 1.5),
    _build_skill("RadiantRecovery", (72, 76, 79, 84), (0.5, 0.25, 0.25, 0.5),
                 "Radiant", "MusicBox", 12, 18, 2.0),
    _build_skill("FortesBlessing", (60, 67, 72, 76, 84), (0.25, 0.25, 0.25, 0.25, 0.75),
                 "Forte", "Trumpet", 16, 22, 2.5),
])

# AoE multi-target skills (daemon-generated)
DEMO_SKILLS.extend([
    _build_skill("CascadeFury", (36, 48, 60, 72, 84, 96), (0.125,) * 6,
                 "Tide", "Drums", 18, 30, 2.0),
    _build_skill("StormBurst", (64, 71, 76, 79, 84, 88), (0.125,) * 4 + (0.25, 0.5),
                 "Gale", "Violin", 20, 32, 2.2),
    _build_skill("ArcaneNova", (60, 64, 67, 72, 76, 84, 96), (0.125,) * 5 + (0.25, 0.75),
                 "Arcane", "Harp", 22, 35, 2.5),
])


def list_skills() -> list[dict]:
    return [s.to_dict() for s in DEMO_SKILLS]


def get_skill(skill_id: str) -> Optional[MelodiaSongSkillRecipe]:
    for s in DEMO_SKILLS:
        if s.skill_id == skill_id:
            return s
    return None


def audit_skill_summary() -> dict:
    return {
        "count": len(DEMO_SKILLS),
        "levels": sorted(set(s.mechanic_level for s in DEMO_SKILLS)),
        "instruments": list(set(s.instrument for s in DEMO_SKILLS)),
        "elements": list(set(s.element for s in DEMO_SKILLS)),
    }
