#!/usr/bin/env python
"""
VDM Fabric Mountain Baker — Houdini SOP → Vector Displacement Map

Scaffold for Faraway Mother fabric ridges. Bakes XYZ vector displacement
that heightmaps cannot (overhangs, drape).

Usage:
  hython Tools/Houdini/vdm_fabric_mountains/vdm_fabric_baker.py --seed 20260829 --res 4096 --variant A
  hython Tools/Houdini/vdm_fabric_mountains/vdm_fabric_baker.py --seed 20260829 --res 1024 --variant B --dry-run

Output: Saved/Audit/vdm_fabric/T_FarawayMother_Fabric_VDM_[A/B/C].exr (32f RGB=XYZ, A=mask)
Manifest: specs/vdm/faraway_mother_vdm_manifest.v1.json
"""
from __future__ import annotations
import argparse
import json
import hashlib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SEED = 20260829
VARIANTS = ["A", "B", "C"]  # A: ridge, B: valley, C: haze drape

def bake_vdm(seed: int, res: int, variant: str, dry_run: bool = False):
    """Houdini SOP VDM bake — template. Requires hython + Indie/Core (Apprentice caps at 1920)."""
    out_dir = PROJECT_ROOT / "Saved" / "Audit" / "vdm_fabric"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Houdini SOP network (template string — actual cook needs hython)
    hip_template = f"""
# Houdini SOP VDM Baker — Faraway Mother Fabric Mountain
# Generated by vdm_fabric_baker.py seed={seed} res={res} variant={variant}
import hou
hou.hipFile.clear()
geo = hou.node(\"/obj\").createNode(\"geo\", \"fabric_mountain\")
# 1. Base plane 10m x 10m, 200x200 quads, rest attribute
grid = geo.createNode(\"grid\", \"base_plane\")
grid.parm(\"sizex\").set(10); grid.parm(\"sizey\").set(10)
grid.parm(\"rows\").set(200); grid.parm(\"cols\").set(200)
rest = geo.createNode(\"attribcreate\", \"rest\")
rest.parm(\"name\").set(\"rest\"); rest.parm(\"class\").set(2)  # Point
rest.setInput(0, grid)
# 2. VEX fold: sin drape + Chladni (3,5) jacquard
wrangle = geo.createNode(\"attribwrangle\", \"fabric_fold\")
wrangle.parm(\"snippet\").set('''
float freq = 3.0 + ch(\"foldFreq\"); float depth = ch(\"foldDepth\");
@P += sin(@P.x*freq) * depth * @N + noise(@P*2.0)*0.1;
@Cd = relBbox(0, @P);  // For mask
''')
wrangle.parm(\"foldFreq\").set(3.0 if variant==\"A\" else 1.5)
wrangle.parm(\"foldDepth\").set(0.3 if variant==\"A\" else 0.1)
wrangle.setInput(0, rest)
# 3. Labs Maps Baker — Vector Displacement
baker = geo.createNode(\"labs::maps_baker\", \"vdm_baker\")
baker.parm(\"highResInput\").set(wrangle.path())
baker.parm(\"lowResInput\").set(grid.path())
baker.parm(\"mode\").set(\"vector\")  # Vector displacement
baker.parm(\"resolution\").set({res})
baker.parm(\"seed\").set({seed})
# 4. COP File Output — 32f EXR, RGB=XYZ
rop = geo.createNode(\"rop_geometry\", \"vdm_output\")
rop.parm(\"soppath\").set(baker.path())
rop.parm(\"sopoutput\").set(\"$HIP/../Saved/Audit/vdm_fabric/T_FarawayMother_Fabric_VDM_{variant}.exr\")
# Cook: rop.parm(\"execute\").pressButton()
"""
    
    out_file = out_dir / f"T_FarawayMother_Fabric_VDM_{variant}.exr"
    
    if dry_run:
        print(f"[DRY-RUN] Would bake VDM {variant} seed={seed} res={res} -> {out_file}")
        print(f"[DRY-RUN] HIP template chars: {len(hip_template)}")
        # Write template for inspection
        template_path = out_dir / f"vdm_baker_{variant}_template.py"
        template_path.write_text(hip_template)
        print(f"[DRY-RUN] Wrote template: {template_path}")
        return {"variant": variant, "seed": seed, "res": res, "out": str(out_file), "dry_run": True, "template": str(template_path)}

    # Real bake requires hython — this scaffold is the contract, not the cook
    # In hython env: exec(hip_template) then rop cook
    try:
        import hou
        exec(hip_template)
        print(f"[BAKE] VDM {variant} bake complete -> {out_file}")
        return {"variant": variant, "seed": seed, "res": res, "out": str(out_file), "dry_run": False}
    except ImportError:
        print(f"[SCAFFOLD] hython not available — wrote template for later cook: {variant}")
        template_path = out_dir / f"vdm_baker_{variant}_template.py"
        template_path.write_text(hip_template)
        return {"variant": variant, "seed": seed, "res": res, "out": str(out_file), "dry_run": True, "template": str(template_path), "note": "hython required for real cook"}

def main():
    ap = argparse.ArgumentParser(description="VDM Fabric Mountain Baker — Faraway Mother")
    ap.add_argument("--seed", type=int, default=SEED, help="Seed (default 20260829)")
    ap.add_argument("--res", type=int, default=4096, help="Resolution 1024/2048/4096")
    ap.add_argument("--variant", choices=VARIANTS, default="A", help="Variant A/B/C")
    ap.add_argument("--all", action="store_true", help="Bake all variants")
    ap.add_argument("--dry-run", action="store_true", help="Dry run (no hython cook)")
    args = ap.parse_args()
    
    variants = VARIANTS if args.all else [args.variant]
    results = []
    for v in variants:
        r = bake_vdm(args.seed, args.res, v, dry_run=args.dry_run)
        results.append(r)
    
    # Write manifest
    manifest_path = PROJECT_ROOT / "specs" / "vdm" / "faraway_mother_vdm_manifest.v1.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema": "melodia.vdm_manifest.v1",
        "seed": args.seed,
        "resolution": args.res,
        "variants": results,
        "ue_path": "/Game/EnvSandbox/Textures/FarawayMother/VDM/",
        "material": "M_Master_FarawayMother_Fabric (WPO)",
        "lod_fade": {"LOD0": 1.0, "LOD1": 0.75, "LOD2": 0.3, "LOD3": 0.0},
        "hash": hashlib.sha256(json.dumps(results, sort_keys=True).encode()).hexdigest()[:16]
    }
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"[MANIFEST] Wrote {manifest_path} hash={manifest['hash']}")
    print(json.dumps(manifest, indent=2))

if __name__ == "__main__":
    main()
