"""Apply the Sea Above heatmap dress manifest into LV_SeaAbove_Prototype.

Editor lane (Monolith :9316, single instance). Reads
specs/water_veil/sea_above_heatmap_dress.v1.json (generated by
build_sea_above_heatmap_dress.py from real sampled terrain) and places each
point HEIGHT-AWARE: a real line-trace raycast snaps Z = landscape surface +
clearance. No floating pieces (BS_GodFile preference #2).

Terrain points (TideSeam/ReefGarden/AbyssFloor) raycast to the landscape.
CathedralHalo points use their authored Z directly (placed on the drowned
cathedral tier planes, not on terrain).

Evidence standard: this script IS the harness that ran; it writes
Saved/Audit/sea_above_dress_report.json with per-placement final Z vs raycast
Z so the result is re-checkable.

Run: ./.venv/Scripts/python.exe Tools/PCG/apply_sea_above_heatmap_dress.py [--manifest ...] [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import urllib.request

MCP = "http://localhost:9316/mcp"
# Actor label prefix so placed pieces are identifiable + re-runnable
PREFIX = "SA_HM_"

# Editor-side python (flattened by json.dumps; newlines OK inside the string
# once serialized — the MCP layer accepts them).
EDITOR_SCRIPT = '''
import unreal, json, math

manifest_path = '__MANIFEST_PATH__'
prefix = '__PREFIX__'
dry = __DRY__

with open(manifest_path, encoding="utf-8") as f:
    man = json.load(f)

world = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
existing = {a.get_actor_label() for a in eas.get_all_level_actors()}

total = len(man["placements"])
placed = 0
skipped = 0
failed = []
report = {"manifest": manifest_path, "total": total, "placed": 0, "skipped": 0, "failed": [], "deltas": []}

ign = unreal.Array(unreal.Actor)

def raycast_z(x, y):
    start = unreal.Vector(float(x), float(y), 90000.0)
    end = unreal.Vector(float(x), float(y), -90000.0)
    hit = unreal.SystemLibrary.line_trace_single(
        world, start, end, unreal.TraceTypeQuery.ECC_VISIBILITY, False, ign,
        unreal.DrawDebugTrace.NONE, True,
        unreal.LinearColor(1,0,0,1), unreal.LinearColor(0,1,0,1), 0.0)
    d = hit.to_dict() if hit else {}
    if d.get("blocking_hit"):
        return float(d["impact_point"].z)
    return None

def load_asset(path):
    return unreal.EditorAssetLibrary.load_asset(path)

for p in man["placements"]:
    label = prefix + p["id"]
    if label in existing:
        skipped += 1
        continue
    mesh_path = p["mesh"]
    x, y, az = p["position"][0], p["position"][1], None
    clearance = p["clearance_cm"]
    is_bp = mesh_path.endswith(".BP_Jelly_Cathedral")
    try:
        if is_bp or clearance <= 0.0:
            z = p["position"][2]  # tier plane, no raycast
        else:
            rz = raycast_z(x, y)
            if rz is not None:
                z = rz + clearance
            else:
                z = p["position"][2]  # fall back to authored height (shouldn't happen on landscape)
                failed.append({"id": p["id"], "reason": "raycast_miss"})
        rot = unreal.Rotator(*p["rotation"])
        scl = unreal.Vector(*p["scale"])
        if is_bp:
            bp = load_asset(mesh_path)
            cls = bp.generated_class()
            actor = unreal.EditorLevelLibrary.spawn_actor_from_class(cls, unreal.Vector(x, y, z), rot)
            actor.set_actor_label(label)
        else:
            mesh = load_asset(mesh_path)
            if mesh is None:
                failed.append({"id": p["id"], "reason": "mesh_missing"})
                continue
            actor = unreal.EditorLevelLibrary.spawn_actor_from_object(mesh, unreal.Vector(x, y, z), rot)
            actor.set_actor_label(label)
            actor.set_actor_scale3d(scl)
            comp = actor.get_component_by_class(unreal.StaticMeshComponent)
            if comp is not None:
                mi = load_asset(p["material"])
                if mi is not None:
                    comp.set_editor_property("override_materials", [mi])
        placed += 1
        report["deltas"].append({"id": p["id"], "x": round(x,1), "y": round(y,1),
                                   "authored_z": round(p["position"][2],1), "final_z": round(z,1),
                                   "clearance": clearance})
    except Exception as e:
        failed.append({"id": p["id"], "reason": str(e)[:200]})

report["placed"] = placed
report["skipped"] = skipped
report["failed"] = failed
out_path = r"Saved/Audit/sea_above_dress_report.json"
import os
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(report, f, indent=2)
print(json.dumps({"placed": placed, "skipped": skipped, "failed": len(failed), "report": out_path}))
'''

def call_editor(script: str) -> dict:
    payload = {
        "jsonrpc": "2.0", "id": 1, "method": "tools/call",
        "params": {"name": "editor_query",
                   "arguments": {"action": "run_python", "params": {"command": script}}},
    }
    req = urllib.request.Request(MCP, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=600) as r:
        return json.loads(r.read().decode())


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default="specs/water_veil/sea_above_heatmap_dress.v1.json")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the editor script without executing")
    args = ap.parse_args(argv)

    manifest = Path(args.manifest).resolve()
    if not manifest.exists():
        print(f"manifest missing: {manifest}")
        return 1

    script = (
        EDITOR_SCRIPT
        .replace("__MANIFEST_PATH__", str(manifest).replace("\\", "/"))
        .replace("__PREFIX__", PREFIX)
        .replace("__DRY__", repr(args.dry_run))
    )

    if args.dry_run:
        print(script)
        return 0

    resp = call_editor(script)
    # Unwrap JSON-RPC content
    try:
        content = resp["result"]["content"]
        text = "".join(c.get("text", "") for c in content)
        # the editor prints our json at the end after mode lines
        print(text[:4000])
    except Exception as e:
        print("unexpected response:", str(e)[:500])
        print(json.dumps(resp)[:2000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())