import unreal

# The delegate signature function generated by UHT for FMelodiaBattleCompleted
for path in (
    "/Script/BS_GodFile.MelodiaNarrativeSubsystem:FMelodiaBattleCompleted__DelegateSignature",
    "/Script/BS_GodFile.FMelodiaBattleCompleted__DelegateSignature",
):
    o = unreal.find_object(None, path)
    print("find:", path, "->", o)
    if o:
        break

ASSET = "/Game/MelodiaIntegration/Blueprints/Opening/BP_MelodiaSirMelodiousMorningIntro"

# Get the BP's actual UFunction for HandleBattleCompleted from skeleton class
bp = unreal.load_asset(ASSET)
print("bp:", bp)
# iterate class functions via refection attr
gc = bp.generated_class()
names = [n for n in dir(gc) if "andle" in n and not n.startswith("_")]
print("gc handles:", names)