import unreal
import json
import math
import random

# ============================================================
# ATLANTIS KITBASH INTEGRATION — Methodical Review + Placement
# ============================================================

random.seed(2026)

# Cathedral center
CX, CY, CZ = 0, 0, 13405

# ============================================================
# ATLANTIS MESH CATEGORIES (333 meshes total)
# ============================================================

ATLANTIS_MESHES = {
    # Structural
    "arch": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchA.SM_ATL_Palace_ArchA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchB.SM_ATL_Palace_ArchB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchC.SM_ATL_Palace_ArchC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchD.SM_ATL_Palace_ArchD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchE.SM_ATL_Palace_ArchE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchF.SM_ATL_Palace_ArchF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchG.SM_ATL_Palace_ArchG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchH.SM_ATL_Palace_ArchH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchI.SM_ATL_Palace_ArchI",
    ],
    "arches": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchesA.SM_ATL_Palace_ArchesA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ArchesB.SM_ATL_Palace_ArchesB",
    ],
    "columns": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsA.SM_ATL_Palace_ColumnsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsB.SM_ATL_Palace_ColumnsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsC.SM_ATL_Palace_ColumnsC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsD.SM_ATL_Palace_ColumnsD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsE.SM_ATL_Palace_ColumnsE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsF.SM_ATL_Palace_ColumnsF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsG.SM_ATL_Palace_ColumnsG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsH.SM_ATL_Palace_ColumnsH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsI.SM_ATL_Palace_ColumnsI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsJ.SM_ATL_Palace_ColumnsJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsK.SM_ATL_Palace_ColumnsK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsL.SM_ATL_Palace_ColumnsL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsM.SM_ATL_Palace_ColumnsM",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsN.SM_ATL_Palace_ColumnsN",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsO.SM_ATL_Palace_ColumnsO",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsP.SM_ATL_Palace_ColumnsP",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsQ.SM_ATL_Palace_ColumnsQ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsR.SM_ATL_Palace_ColumnsR",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsS.SM_ATL_Palace_ColumnsS",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsT.SM_ATL_Palace_ColumnsT",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsU.SM_ATL_Palace_ColumnsU",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsV.SM_ATL_Palace_ColumnsV",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsW.SM_ATL_Palace_ColumnsW",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnsX.SM_ATL_Palace_ColumnsX",
    ],
    "columnade": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnadeA.SM_ATL_Palace_ColumnadeA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ColumnadeB.SM_ATL_Palace_ColumnadeB",
    ],
    "base": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseA.SM_ATL_Palace_BaseA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseB.SM_ATL_Palace_BaseB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseC.SM_ATL_Palace_BaseC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseD.SM_ATL_Palace_BaseD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseE.SM_ATL_Palace_BaseE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseF.SM_ATL_Palace_BaseF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseG.SM_ATL_Palace_BaseG",
    ],
    "basecolumns": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseColumnsA.SM_ATL_Palace_BaseColumnsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseColumnsB.SM_ATL_Palace_BaseColumnsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BaseColumnsC.SM_ATL_Palace_BaseColumnsC",
    ],
    "building": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingA.SM_ATL_Palace_BuildingA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingB.SM_ATL_Palace_BuildingB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingC.SM_ATL_Palace_BuildingC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingD.SM_ATL_Palace_BuildingD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingE.SM_ATL_Palace_BuildingE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingF.SM_ATL_Palace_BuildingF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingG.SM_ATL_Palace_BuildingG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingH.SM_ATL_Palace_BuildingH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingI.SM_ATL_Palace_BuildingI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingJ.SM_ATL_Palace_BuildingJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingK.SM_ATL_Palace_BuildingK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingL.SM_ATL_Palace_BuildingL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingM.SM_ATL_Palace_BuildingM",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingN.SM_ATL_Palace_BuildingN",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingO.SM_ATL_Palace_BuildingO",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BuildingP.SM_ATL_Palace_BuildingP",
    ],
    "dome": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DomeA.SM_ATL_Palace_DomeA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DomeB.SM_ATL_Palace_DomeB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DomeC.SM_ATL_Palace_DomeC",
    ],
    "roof": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_RoofA.SM_ATL_Palace_RoofA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_RoofB.SM_ATL_Palace_RoofB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_RoofC.SM_ATL_Palace_RoofC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_RoofD.SM_ATL_Palace_RoofD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_RoofE.SM_ATL_Palace_RoofE",
    ],
    "stairs": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsA.SM_ATL_Palace_StairsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsB.SM_ATL_Palace_StairsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsC.SM_ATL_Palace_StairsC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsD.SM_ATL_Palace_StairsD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsE.SM_ATL_Palace_StairsE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StairsF.SM_ATL_Palace_StairsF",
    ],
    "steps": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StepsA.SM_ATL_Palace_StepsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StepsB.SM_ATL_Palace_StepsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StepsC.SM_ATL_Palace_StepsC",
    ],
    "floor": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FloorA.SM_ATL_Palace_FloorA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FloorB.SM_ATL_Palace_FloorB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FloorC.SM_ATL_Palace_FloorC",
    ],
    "decorative": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BannerA.SM_ATL_Palace_BannerA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BannerB.SM_ATL_Palace_BannerB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BannerC.SM_ATL_Palace_BannerC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BannerD.SM_ATL_Palace_BannerD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_Cornice.SM_ATL_Palace_Cornice",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DecorativeVaseA.SM_ATL_Palace_DecorativeVaseA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DecorativeVaseB.SM_ATL_Palace_DecorativeVaseB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DecorativeVaseC.SM_ATL_Palace_DecorativeVaseC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_DecorativeVaseD.SM_ATL_Palace_DecorativeVaseD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FountainA.SM_ATL_Palace_FountainA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FountainB.SM_ATL_Palace_FountainB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_FountainC.SM_ATL_Palace_FountainC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailA.SM_ATL_Palace_GuardrailA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailB.SM_ATL_Palace_GuardrailB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailC.SM_ATL_Palace_GuardrailC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailD.SM_ATL_Palace_GuardrailD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailE.SM_ATL_Palace_GuardrailE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailF.SM_ATL_Palace_GuardrailF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailG.SM_ATL_Palace_GuardrailG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailH.SM_ATL_Palace_GuardrailH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailI.SM_ATL_Palace_GuardrailI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GuardrailJ.SM_ATL_Palace_GuardrailJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_NicheA.SM_ATL_Palace_NicheA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_NicheB.SM_ATL_Palace_NicheB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_NicheC.SM_ATL_Palace_NicheC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_NicheD.SM_ATL_Palace_NicheD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_NicheE.SM_ATL_Palace_NicheE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_OrnamentsA.SM_ATL_Palace_OrnamentsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_OrnamentsB.SM_ATL_Palace_OrnamentsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_OrnamentsC.SM_ATL_Palace_OrnamentsC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_OrnamentsD.SM_ATL_Palace_OrnamentsD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_OrnamentsE.SM_ATL_Palace_OrnamentsE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PergolaA.SM_ATL_Palace_PergolaA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PergolaB.SM_ATL_Palace_PergolaB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PergolaC.SM_ATL_Palace_PergolaC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PergolaD.SM_ATL_Palace_PergolaD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterA.SM_ATL_Palace_PlanterA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterB.SM_ATL_Palace_PlanterB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterC.SM_ATL_Palace_PlanterC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterD.SM_ATL_Palace_PlanterD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterE.SM_ATL_Palace_PlanterE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterF.SM_ATL_Palace_PlanterF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterG.SM_ATL_Palace_PlanterG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterH.SM_ATL_Palace_PlanterH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterI.SM_ATL_Palace_PlanterI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterJ.SM_ATL_Palace_PlanterJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterK.SM_ATL_Palace_PlanterK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterL.SM_ATL_Palace_PlanterL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterM.SM_ATL_Palace_PlanterM",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterN.SM_ATL_Palace_PlanterN",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterO.SM_ATL_Palace_PlanterO",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterP.SM_ATL_Palace_PlanterP",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterQ.SM_ATL_Palace_PlanterQ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterR.SM_ATL_Palace_PlanterR",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterS.SM_ATL_Palace_PlanterS",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterT.SM_ATL_Palace_PlanterT",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterU.SM_ATL_Palace_PlanterU",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterV.SM_ATL_Palace_PlanterV",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_PlanterW.SM_ATL_Palace_PlanterW",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TorchA.SM_ATL_Palace_TorchA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TorchB.SM_ATL_Palace_TorchB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TorchC.SM_ATL_Palace_TorchC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TorchD.SM_ATL_Palace_TorchD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TorchE.SM_ATL_Palace_TorchE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseA.SM_ATL_Palace_VaseA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseB.SM_ATL_Palace_VaseB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseC.SM_ATL_Palace_VaseC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseD.SM_ATL_Palace_VaseD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseE.SM_ATL_Palace_VaseE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseF.SM_ATL_Palace_VaseF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseG.SM_ATL_Palace_VaseG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseH.SM_ATL_Palace_VaseH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseI.SM_ATL_Palace_VaseI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseJ.SM_ATL_Palace_VaseJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_VaseK.SM_ATL_Palace_VaseK",
    ],
    "seating": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BenchA.SM_ATL_Palace_BenchA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BenchB.SM_ATL_Palace_BenchB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BenchC.SM_ATL_Palace_BenchC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BenchD.SM_ATL_Palace_BenchD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BenchE.SM_ATL_Palace_BenchE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ChairA.SM_ATL_Palace_ChairA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ChairB.SM_ATL_Palace_ChairB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ChairC.SM_ATL_Palace_ChairC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StoolA.SM_ATL_Palace_StoolA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StoolB.SM_ATL_Palace_StoolB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_StoolC.SM_ATL_Palace_StoolC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TableA.SM_ATL_Palace_TableA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TableB.SM_ATL_Palace_TableB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TableC.SM_ATL_Palace_TableC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TableD.SM_ATL_Palace_TableD",
    ],
    "nature": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeA.SM_ATL_Palace_TreeA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeB.SM_ATL_Palace_TreeB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeC.SM_ATL_Palace_TreeC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeD.SM_ATL_Palace_TreeD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeE.SM_ATL_Palace_TreeE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeF.SM_ATL_Palace_TreeF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeG.SM_ATL_Palace_TreeG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeH.SM_ATL_Palace_TreeH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeI.SM_ATL_Palace_TreeI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeJ.SM_ATL_Palace_TreeJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeK.SM_ATL_Palace_TreeK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeL.SM_ATL_Palace_TreeL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeM.SM_ATL_Palace_TreeM",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeN.SM_ATL_Palace_TreeN",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeO.SM_ATL_Palace_TreeO",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeP.SM_ATL_Palace_TreeP",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeQ.SM_ATL_Palace_TreeQ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeR.SM_ATL_Palace_TreeR",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_TreeS.SM_ATL_Palace_TreeS",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsA.SM_ATL_Palace_ShrubsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsB.SM_ATL_Palace_ShrubsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsC.SM_ATL_Palace_ShrubsC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsD.SM_ATL_Palace_ShrubsD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsE.SM_ATL_Palace_ShrubsE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsF.SM_ATL_Palace_ShrubsF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsG.SM_ATL_Palace_ShrubsG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsH.SM_ATL_Palace_ShrubsH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsI.SM_ATL_Palace_ShrubsI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsJ.SM_ATL_Palace_ShrubsJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsK.SM_ATL_Palace_ShrubsK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsL.SM_ATL_Palace_ShrubsL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsM.SM_ATL_Palace_ShrubsM",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsN.SM_ATL_Palace_ShrubsN",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsO.SM_ATL_Palace_ShrubsO",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsP.SM_ATL_Palace_ShrubsP",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsQ.SM_ATL_Palace_ShrubsQ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsR.SM_ATL_Palace_ShrubsR",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsS.SM_ATL_Palace_ShrubsS",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsT.SM_ATL_Palace_ShrubsT",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsU.SM_ATL_Palace_ShrubsU",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsV.SM_ATL_Palace_ShrubsV",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsW.SM_ATL_Palace_ShrubsW",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_ShrubsX.SM_ATL_Palace_ShrubsX",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingA.SM_ATL_Palace_IvyHangingA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingB.SM_ATL_Palace_IvyHangingB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingC.SM_ATL_Palace_IvyHangingC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingD.SM_ATL_Palace_IvyHangingD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingE.SM_ATL_Palace_IvyHangingE",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingF.SM_ATL_Palace_IvyHangingF",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingG.SM_ATL_Palace_IvyHangingG",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingH.SM_ATL_Palace_IvyHangingH",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingI.SM_ATL_Palace_IvyHangingI",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingJ.SM_ATL_Palace_IvyHangingJ",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingK.SM_ATL_Palace_IvyHangingK",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingL.SM_ATL_Palace_IvyHangingL",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_IvyHangingM.SM_ATL_Palace_IvyHangingM",
    ],
    "props": [
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_Barrel.SM_ATL_Palace_Barrel",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelRackA.SM_ATL_Palace_BarrelRackA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelRackB.SM_ATL_Palace_BarrelRackB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelRackC.SM_ATL_Palace_BarrelRackC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelRackD.SM_ATL_Palace_BarrelRackD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelsA.SM_ATL_Palace_BarrelsA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelsB.SM_ATL_Palace_BarrelsB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelsC.SM_ATL_Palace_BarrelsC",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BarrelsD.SM_ATL_Palace_BarrelsD",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BasketA.SM_ATL_Palace_BasketA",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_BasketB.SM_ATL_Palace_BasketB",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_GrapesStand.SM_ATL_Palace_GrapesStand",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_Harp.SM_ATL_Palace_Harp",
        "/Game/EnvSandbox/Meshes/Atlantis/SM_ATL_Palace_HayStack.SM_ATL_Palace_HayStack",
    ],
}

# Count total
total = sum(len(v) for v in ATLANTIS_MESHES.values())
print(f"Total Atlantis meshes: {total}")

# Print counts by category
for cat, meshes in ATLANTIS_MESHES.items():
    print(f"  {cat}: {len(meshes)}")
