"""UE Agent Status Panel - Shows agent status in Unreal Editor.

Extends init_unreal.py to provide real-time agent feedback.
Creates a text log that can be viewed in the Output Log window.

Candidate Owner Agent: World Integration Agent (WIA)
"""
import unreal
from pathlib import Path
import json

AGENT_MEMORY_DIR = Path(__file__).resolve().parent.parent / "Saved" / "AgentMemory"

# Agent status icons/colors
AGENT_ICONS = {
    "geometry": "🏛️",
    "material": "🎨",
    "placement": "📍",
    "integration": "🔗",
    "qa": "🛡️",
}

AGENT_COLORS = {
    "geometry": unreal.LinearColor.GREEN,
    "material": unreal.LinearColor.YELLOW,
    "placement": unreal.LinearColor.BLUE,
    "integration": unreal.LinearColor.CYAN,
    "qa": unreal.LinearColor.MAGENTA,
}


def get_agent_status_markdown() -> str:
    """Generate markdown status for all agents."""
    loop_files = {
        "geometry": Path(__file__).resolve().parent.parent / "deploy" / "SURREAL_ARCH_LOOP_STOP",
        "material": Path(__file__).resolve().parent.parent / "deploy" / "MATERIAL_AAA_LOOP.pid",
        "placement": Path(__file__).resolve().parent.parent / "deploy" / "SDF_FACTORY_LOOP.pid",
        "integration": Path(__file__).resolve().parent.parent / "deploy" / "SURREAL_WORLD_LOOP_STOP",
        "qa": Path(__file__).resolve().parent.parent / "Saved" / "Audit" / "hermes_health.json",
    }
    
    lines = ["# Agent Status Report", ""]
    
    for agent, icon in AGENT_ICONS.items():
        loop_stop = loop_files.get(agent)
        if loop_stop and loop_stop.exists():
            status = "🔴 STOPPED"
            if agent == "qa":
                try:
                    health = json.loads(loop_stop.read_text())
                    blessings_count = health.get("blessings", {}).get("blessings_count", 0)
                    status = f"🟢 {blessings_count} blessings healthy"
                except Exception:
                    status = "🔴 HEALTH ERROR"
        else:
            status = "🟢 RUNNING"
        
        lines.append(f"{icon} **{agent.title()} Agent**: {status}")
    
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Agent Bridge MCP*")
    
    return "\n".join(lines)


def log_agent_status() -> None:
    """Log agent status to UE output log."""
    unreal.log("=" * 50)
    unreal.log("[AgentBridge] Agent Status:")
    
    for agent, icon in AGENT_ICONS.items():
        loop_files = {
            "geometry": Path(__file__).resolve().parent.parent / "deploy" / "SURREAL_ARCH_LOOP_STOP",
            "material": Path(__file__).resolve().parent.parent / "deploy" / "MATERIAL_AAA_LOOP.pid",
            "placement": Path(__file__).resolve().parent.parent / "deploy" / "SDF_FACTORY_LOOP.pid",
            "integration": Path(__file__).resolve().parent.parent / "deploy" / "SURREAL_WORLD_LOOP_STOP",
            "qa": Path(__file__).resolve().parent.parent / "Saved" / "Audit" / "hermes_health.json",
        }
        
        loop_stop = loop_files.get(agent)
        if loop_stop and loop_stop.exists():
            status = "STOPPED"
            if agent == "qa":
                try:
                    health = json.loads(loop_stop.read_text())
                    blessings_count = health.get("blessings", {}).get("blessings_count", 0)
                    status = f"{blessings_count} blessings"
                except Exception:
                    status = "ERROR"
        else:
            status = "READY"
        
        unreal.log(f"  [{agent[:2].upper()}] {icon} {agent.title()}: {status}")
    
    unreal.log("=" * 50)


def check_bridge_tools() -> dict:
    """Check available tools from the agent bridge."""
    # This would be called when the bridge MCP is available
    return {
        "delegate_to_agent": "Route intent to any agent",
        "get_agent_status": "Get real-time agent status",
        "get_agent_memory": "Query shared agent memory",
        "run_blessing_evolution": "Generate new blessings",
        "ue_editor_command": "Send commands to UE",
    }


def register_agent_panel():
    """Register agent status in UE editor (called from init_unreal.py)."""
    log_agent_status()
    
    # Add to LiveLink menu for quick access
    menus = unreal.ToolMenus.get()
    live = menus.find_menu("LevelEditor.MainMenu.LiveLink")
    
    if live:
        # Add Agent Status entry
        entry = unreal.ToolMenuEntry(
            name="AgentBridgeStatus",
            type=unreal.MultiBlockType.MENU_ENTRY,
            user_interface_object_version=unreal.VersionedActionBase.VersionedAction
        )
        entry.set_label("Agent Bridge Status")
        
        # Python command to show status
        py_cmd = (
            "import agent_status_panel; "
            "agent_status_panel.log_agent_status(); "
            "unreal.log('[AgentBridge] Full status logged above')"
        )
        entry.set_string_command(
            type=unreal.ToolMenuStringCommandType.PYTHON,
            custom_type_name="",
            string=py_cmd
        )
        
        live.add_menu_entry("Portfolio", entry)
        menus.refresh_all_widgets()
        unreal.log("[AgentBridge] Agent status panel registered in LiveLink menu")
    
    return True


if __name__ == "__main__":
    # Test when run standalone
    print(get_agent_status_markdown())