"""UE Post-Import Material Resolver — auto-applies .material_map.json crosswalk after FBX import.

Reads the Material Bridge's .material_map.json (generated by Blender's material_bridge.py)
and applies the mapped UE material instances to imported skeletal/static meshes.

Run automatically as a post-import hook, or manually:
  import resolve_material_crosswalk; resolve_material_crosswalk.resolve_imported("SK_Zundamon")

Also works as a batch tool:
  import resolve_material_crosswalk; resolve_material_crosswalk.resolve_all()
"""

import json
import os
import unreal
from pathlib import Path

from melodia_paths import PROJECT_ROOT

# ═══════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════

# Where to look for .material_map.json files
CROSSWALK_SEARCH_PATHS = [
    PROJECT_ROOT / "KitbashExport",
    PROJECT_ROOT / "Exports",
    PROJECT_ROOT / "Content" / "Melodia" / "Characters",
    PROJECT_ROOT.parent / "Imports" / "KitBash3D_Atlantis",
    PROJECT_ROOT.parent / "Imports" / "Oceanology",
    PROJECT_ROOT.parent / "Imports" / "Kenney",
]

# Fallback material if crosswalk entry points to non-existent asset
DEFAULT_MATERIAL = "/Game/EnvSandbox/Materials/Instances/Environment/Stylized/MI_Show_Default"


# ═══════════════════════════════════════════════════════════════════════
# Crosswalk loader
# ═══════════════════════════════════════════════════════════════════════

def find_crosswalk_files() -> list[str]:
    """Find all .material_map.json files in search paths."""
    found = []
    for search_path in CROSSWALK_SEARCH_PATHS:
        if not Path(search_path).is_dir():
            continue
        for root, dirs, files in os.walk(str(search_path)):
            for f in files:
                if f.endswith(".material_map.json"):
                    found.append(os.path.join(root, f))
    return found


def load_crosswalk(path: str) -> dict[str, str]:
    """Load a crosswalk file: {blender_material_name: ue_material_path}."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        unreal.log_warning(f"[Material Resolver] Could not load {path}: {e}")
        return {}


def find_crosswalk_for_asset(asset_name: str) -> dict[str, str]:
    """Find the best crosswalk for a given asset by name matching."""
    crosswalks = find_crosswalk_files()
    # Prefer exact name match
    for cw_path in crosswalks:
        if asset_name.lower() in os.path.basename(cw_path).lower():
            cw = load_crosswalk(cw_path)
            if cw:
                return cw
    # Fallback: load all crosswalks and merge
    merged: dict[str, str] = {}
    for cw_path in crosswalks:
        cw = load_crosswalk(cw_path)
        merged.update(cw)
    return merged


# ═══════════════════════════════════════════════════════════════════════
# Material resolver
# ═══════════════════════════════════════════════════════════════════════

def resolve_material(blender_mat_name: str, crosswalk: dict[str, str]) -> unreal.MaterialInterface | None:
    """Look up UE material instance path from crosswalk and load it."""
    ue_path = crosswalk.get(blender_mat_name)
    if not ue_path:
        return None

    mi = unreal.EditorAssetLibrary.load_asset(ue_path)
    if mi:
        return mi

    # Try fuzzy: remove MI_ prefix, try different casing
    for cw_name, cw_path in crosswalk.items():
        if blender_mat_name.lower() in cw_name.lower() or cw_name.lower() in blender_mat_name.lower():
            mi = unreal.EditorAssetLibrary.load_asset(cw_path)
            if mi:
                unreal.log(f"[Material Resolver] Fuzzy match: {blender_mat_name} → {cw_path}")
                return mi

    return None


def apply_to_skeletal_mesh(mesh_path: str, crosswalk: dict[str, str]) -> int:
    """Apply crosswalk materials to a SkeletalMesh asset's material slots."""
    sk = unreal.EditorAssetLibrary.load_asset(mesh_path)
    if not sk:
        unreal.log_warning(f"[Material Resolver] Cannot load {mesh_path}")
        return 0

    materials = sk.get_editor_property("materials")
    applied = 0

    for i, mat_slot in enumerate(materials):
        slot_name = str(mat_slot.get_editor_property("material_slot_name") or f"Slot_{i}")

        # Try to match slot name to crosswalk
        mi = resolve_material(slot_name, crosswalk)
        if not mi:
            # Try with M_ or MI_ prefix variations
            for prefix in ["MI_", "M_", ""]:
                test_name = f"{prefix}{slot_name}"
                mi = resolve_material(test_name, crosswalk)
                if mi:
                    break

        if mi:
            materials[i].set_editor_property("material_interface", mi)
            applied += 1
            unreal.log(f"[Material Resolver] Slot {i} '{slot_name}' → {mi.get_path_name()}")

    if applied > 0:
        sk.set_editor_property("materials", materials)
        unreal.EditorAssetLibrary.save_asset(mesh_path)
        unreal.log(f"[Material Resolver] Applied {applied}/{len(materials)} materials to {mesh_path}")
    else:
        unreal.log(f"[Material Resolver] No materials matched for {mesh_path} (slots: {[str(m.get_editor_property('material_slot_name')) for m in materials]})")

    return applied


def apply_to_static_mesh(mesh_path: str, crosswalk: dict[str, str]) -> int:
    """Apply crosswalk materials to a StaticMesh asset."""
    sm = unreal.EditorAssetLibrary.load_asset(mesh_path)
    if not sm:
        return 0

    materials = sm.get_editor_property("static_materials")
    applied = 0

    for i, mat_slot in enumerate(materials):
        slot_name = str(mat_slot.get_editor_property("material_slot_name") or f"Slot_{i}")
        mi = resolve_material(slot_name, crosswalk)
        if not mi:
            for prefix in ["MI_", "M_", ""]:
                mi = resolve_material(f"{prefix}{slot_name}", crosswalk)
                if mi:
                    break

        if mi:
            materials[i].set_editor_property("material_interface", mi)
            applied += 1

    if applied > 0:
        sm.set_editor_property("static_materials", materials)
        unreal.EditorAssetLibrary.save_asset(mesh_path)

    return applied


# ═══════════════════════════════════════════════════════════════════════
# Post-import hook
# ═══════════════════════════════════════════════════════════════════════

def on_asset_imported(asset_path: str):
    """Post-import hook — resolve materials automatically after FBX import.

    Call this from an Unreal import callback or manually.
    """
    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    if not asset:
        return

    asset_name = unreal.EditorAssetLibrary.get_asset_name(asset_path)
    crosswalk = find_crosswalk_for_asset(asset_name)

    if not crosswalk:
        unreal.log(f"[Material Resolver] No crosswalk found for {asset_name}")
        return

    asset_class = asset.get_class().get_name()

    if asset_class == "SkeletalMesh":
        applied = apply_to_skeletal_mesh(asset_path, crosswalk)
    elif asset_class == "StaticMesh":
        applied = apply_to_static_mesh(asset_path, crosswalk)
    else:
        unreal.log(f"[Material Resolver] Skipping {asset_class}: {asset_path}")
        return

    if applied:
        unreal.log(f"[Material Resolver] ✓ Auto-resolved {applied} materials for {asset_name}")


# ═══════════════════════════════════════════════════════════════════════
# Batch tools
# ═══════════════════════════════════════════════════════════════════════

def resolve_imported(asset_name: str):
    """Resolve materials for a specific imported asset by name."""
    for search_path in [
        "/Game/Melodia/Characters",
        "/Game/EnvSandbox",
        "/Game/LiveLink",
    ]:
        # Try SkeletalMesh then StaticMesh
        for suffix in ["SK_", "SM_", ""]:
            path = f"{search_path}/{suffix}{asset_name}"
            if unreal.EditorAssetLibrary.does_asset_exist(path):
                on_asset_imported(path)
                return path
            # Check subdirectories
            for char_dir in ["Zundamon", "Zunko", "Kiritan", "Itako", "Metan", "Sora", "Tsurugi", "Melusina"]:
                path = f"{search_path}/{char_dir}/{suffix}{asset_name}"
                if unreal.EditorAssetLibrary.does_asset_exist(path):
                    on_asset_imported(path)
                    return path

    unreal.log_warning(f"[Material Resolver] Could not find asset: {asset_name}")
    return None


def resolve_all():
    """Batch resolve materials for all imported ZunZun and Melodia assets."""
    crosswalks = {}
    for cw_path in find_crosswalk_files():
        crosswalks[os.path.basename(cw_path)] = load_crosswalk(cw_path)

    if not crosswalks:
        unreal.log_warning("[Material Resolver] No crosswalk files found")
        return

    unreal.log(f"[Material Resolver] Loaded {len(crosswalks)} crosswalk files")

    total_applied = 0
    for search_path in ["/Game/Melodia/Characters", "/Game/LiveLink"]:
        ar = unreal.AssetRegistryHelpers.get_asset_registry()
        # List all skeletal meshes
        assets = ar.get_assets_by_path(search_path, recursive=True)
        for asset_data in assets:
            if str(asset_data.asset_class) in ["SkeletalMesh", "StaticMesh"]:
                path = str(asset_data.object_path)
                asset_name = str(asset_data.asset_name)
                cw = find_crosswalk_for_asset(asset_name)
                if cw:
                    applied = apply_to_skeletal_mesh(path, cw)
                    total_applied += applied

    unreal.log(f"[Material Resolver] Batch complete: {total_applied} materials applied")


# ═══════════════════════════════════════════════════════════════════════
# Crosswalk generator from existing UE catalog
# ═══════════════════════════════════════════════════════════════════════

def generate_crosswalk_from_catalog(output_path: str | None = None):
    """Auto-generate a .material_map.json from all UE material instances.

    Useful for bootstrapping the crosswalk when no Blender file has been mapped yet.
    """
    catalog: dict[str, str] = {}

    search_roots = [
        "/Game/EnvSandbox/Materials/Instances",
        "/Game/Melodia/Characters",
    ]

    for root in search_roots:
        ar = unreal.AssetRegistryHelpers.get_asset_registry()
        assets = ar.get_assets_by_path(root, recursive=True)
        for ad in assets:
            if str(ad.asset_class) == "MaterialInstanceConstant":
                path = str(ad.object_path)
                name = str(ad.asset_name)
                # Store both full name and cleaned name
                catalog[name] = path
                clean = name.replace("MI_", "").replace("M_", "")
                if clean != name:
                    catalog[clean] = path

    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(__file__), "..", "Content", "Melodia", "ue_catalog_material_map.json"
        )

    output_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2, sort_keys=True)

    unreal.log(f"[Material Resolver] Generated catalog: {len(catalog)} entries → {output_path}")
    return output_path


if __name__ == "__main__":
    resolve_all()
